all: introduced basic dependency checking
Reported-by: Stephen Smalley <stephen.smalley.work@gmail.com>
Signed-off-by: Paul Moore <paul@paul-moore.com>

diff --git a/verify.d/00-dummy b/verify.d/00-dummy
--- a/verify.d/00-dummy
+++ b/verify.d/00-dummy
@@ -18,6 +18,17 @@
 ####
 # functions
 
+function exit_error() {
+	echo ">>> error: $*"
+	exit 1
+}
+
+function dep_check() {
+	for i in $*; do
+		command -v $i > /dev/null || exit_error "$i command not found"
+	done
+}
+
 function git_uncommitted() {
 	local changes=$(git status --porcelain 2>/dev/null | wc -l)
 	[[ $changes -eq 0 ]] && return 1
@@ -26,6 +37,9 @@ function git_uncommitted() {
 
 ####
 # main
+
+# dependency checks
+dep_check git
 
 # check for uncommitted changes
 git_uncommitted && echo ">>> warning: you have uncommitted changes"
diff --git a/verify.d/30-generic_astyle b/verify.d/30-generic_astyle
--- a/verify.d/30-generic_astyle
+++ b/verify.d/30-generic_astyle
@@ -27,6 +27,17 @@ PATHS_ALLOWED=" **/*.c"
 ####
 # functions
 
+function exit_error() {
+	echo ">>> error: $*"
+	exit 1
+}
+
+function dep_check() {
+	for i in $*; do
+		command -v $i > /dev/null || exit_error "$i command not found"
+	done
+}
+
 function git_uncommitted() {
 	local changes=$(git status --porcelain 2>/dev/null | wc -l)
 	[[ $changes -eq 0 ]] && return 1
@@ -56,6 +67,9 @@ function check_file() {
 
 ####
 # main
+
+# dependency checks
+dep_check git astyle
 
 # check for uncommitted changes
 git_uncommitted && echo ">>> WARNING: you have uncommitted changes"
diff --git a/verify.libseccomp.d/90-libseccomp_test b/verify.libseccomp.d/90-libseccomp_test
--- a/verify.libseccomp.d/90-libseccomp_test
+++ b/verify.libseccomp.d/90-libseccomp_test
@@ -18,6 +18,17 @@
 ####
 # functions
 
+function exit_error() {
+	echo ">>> error: $*"
+	exit 1
+}
+
+function dep_check() {
+	for i in $*; do
+		command -v $i > /dev/null || exit_error "$i command not found"
+	done
+}
+
 function repo_top() {
 	local top=$(pwd)
 	while [[ ! -e $top/tools/check-syntax ]]; do
@@ -38,7 +49,10 @@ function git_uncommitted() {
 
 # find the repo top directory
 top=$(repo_top)
-[[ -z $top ]] && exit 1
+[[ -z $top ]] && exit_error "not in a libseccomp directory"
+
+# dependency checks
+dep_check git make
 
 # check for uncommitted changes
 git_uncommitted && echo ">>> WARNING: you have uncommitted changes"
diff --git a/verify.linux.d/10-linux_checkpatch b/verify.linux.d/10-linux_checkpatch
--- a/verify.linux.d/10-linux_checkpatch
+++ b/verify.linux.d/10-linux_checkpatch
@@ -18,6 +18,17 @@
 ####
 # functions
 
+function exit_error() {
+	echo ">>> error: $*"
+	exit 1
+}
+
+function dep_check() {
+	for i in $*; do
+		command -v $i > /dev/null || exit_error "$i command not found"
+	done
+}
+
 function kernel_top() {
 	local top=$(pwd)
 	while [[ ! -e $top/MAINTAINERS ]]; do
@@ -38,10 +49,12 @@ function git_uncommitted() {
 
 # find the kernel top directory
 top=$(kernel_top)
-[[ -z $top ]] && exit 1
+[[ -z $top ]] && exit_error "not in a kernel directory"
+chkpatch="$top/scripts/checkpatch.pl"
+dep_check git $chkpatch
 
 # check for uncommitted changes
 git_uncommitted && echo ">>> WARNING: you have uncommitted changes"
 
 # run checkpatch on the top commit
-git format-patch --stdout -1 | $top/scripts/checkpatch.pl -
+git format-patch --stdout -1 | $chkpatch
diff --git a/verify.linux.d/20-linux_build b/verify.linux.d/20-linux_build
--- a/verify.linux.d/20-linux_build
+++ b/verify.linux.d/20-linux_build
@@ -45,6 +45,17 @@ BUILD_OVERRIDE+="include/uapi/linux/netfilter/*SECMARK.h:security/ "
 ####
 # functions
 
+function exit_error() {
+	echo ">>> error: $*"
+	exit 1
+}
+
+function dep_check() {
+	for i in $*; do
+		command -v $i > /dev/null || exit_error "$i command not found"
+	done
+}
+
 function kernel_top() {
 	local top=$(pwd)
 	while [[ ! -e $top/MAINTAINERS ]]; do
@@ -65,7 +76,10 @@ function git_uncommitted() {
 
 # find the kernel top directory
 top=$(kernel_top)
-[[ -z $top ]] && exit 1
+[[ -z $top ]] && exit_error "not in a kernel directory"
+
+# dependency checks
+dep_check git make
 
 # check for uncommitted changes
 git_uncommitted && echo ">>> WARNING: you have uncommitted changes"
